### ISSUE TITLE
Allow snapshot tests to run outside of a /test folder

### ISSUE THREAD

**Issue by yleflour** [DCzajkowski/snapshy#6]
Our tests are located next to the tested files instead of in the /test folder. Such as:
- /lib/../feature.ex
- /lib/../feature_test.exs

So Snapshy can't locate the "root" path unless the test itself in nested this way
- /lib/../feature.ex
- /lib/../**test**/feature_test.ex

Then, the snapshots are created in:
- test/__snapshots__/feature_test/<test_name>.snap

It would be great to allow Snapshy to generate tests this way instead:
- /lib/../feature.ex
- /lib/../feature_test.exs
- /lib/../__snapshots__/feature_test/<test_name>.snap

I understand if you're willing to discard this request, as it's against standard Elixir practices but it would be a very nice upgrade in our case.

**Comment by DCzajkowski** [comment]
Did you try https://github.com/assert-value/assert_value_elixir? I think it may allow specifying paths, not sure though 🤔

**Comment by yleflour** [comment]
Thank you, I'll check it out, it seems to fit our needs

**Comment by DCzajkowski** [comment]
This should be fixed with #7 :)
